package com.selfie.dto;
// Generated Feb 10, 2017 12:58:55 AM by Hibernate Tools 3.4.0.CR1

/**
 * StudentBills generated by hbm2java
 */
public class StudentBills implements java.io.Serializable {

	private int rollNumber;
	private String studentName;
	private String roomRent;
	private String totalDaysMess;
	private String total;
	private Integer status;

	public StudentBills() {
	}

	public StudentBills(int rollNumber) {
		this.rollNumber = rollNumber;
	}

	public StudentBills(int rollNumber, String studentName, String roomRent, String totalDaysMess, String total,
			Integer status) {
		this.rollNumber = rollNumber;
		this.studentName = studentName;
		this.roomRent = roomRent;
		this.totalDaysMess = totalDaysMess;
		this.total = total;
		this.status = status;
	}

	public int getRollNumber() {
		return this.rollNumber;
	}

	public void setRollNumber(int rollNumber) {
		this.rollNumber = rollNumber;
	}

	public String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	public String getRoomRent() {
		return this.roomRent;
	}

	public void setRoomRent(String roomRent) {
		this.roomRent = roomRent;
	}

	public String getTotalDaysMess() {
		return this.totalDaysMess;
	}

	public void setTotalDaysMess(String totalDaysMess) {
		this.totalDaysMess = totalDaysMess;
	}

	public String getTotal() {
		return this.total;
	}

	public void setTotal(String total) {
		this.total = total;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
