
package com.checkuser;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CMS_Selfie_CheckHttpService", targetNamespace = "http://CMS_Selfie_Check", wsdlLocation = "classpath:wsdl/CMS_Selfie_Check.wsdl")
public class CMSSelfieCheckHttpService
    extends Service
{

    private final static URL CMSSELFIECHECKHTTPSERVICE_WSDL_LOCATION;
    private final static WebServiceException CMSSELFIECHECKHTTPSERVICE_EXCEPTION;
    private final static QName CMSSELFIECHECKHTTPSERVICE_QNAME = new QName("http://CMS_Selfie_Check", "CMS_Selfie_CheckHttpService");

    static {
        URL url = null;
        WebServiceException e = null;
        url =CMSSelfieCheckHttpService.class.getClassLoader().getResource("wsdl/CMS_Selfie_Check.wsdl");
        
        
        CMSSELFIECHECKHTTPSERVICE_WSDL_LOCATION = url;
        CMSSELFIECHECKHTTPSERVICE_EXCEPTION = e;
    }

    public CMSSelfieCheckHttpService() {
        super(__getWsdlLocation(), CMSSELFIECHECKHTTPSERVICE_QNAME);
    }

    public CMSSelfieCheckHttpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMSSELFIECHECKHTTPSERVICE_QNAME, features);
    }

    public CMSSelfieCheckHttpService(URL wsdlLocation) {
        super(wsdlLocation, CMSSELFIECHECKHTTPSERVICE_QNAME);
    }

    public CMSSelfieCheckHttpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMSSELFIECHECKHTTPSERVICE_QNAME, features);
    }

    public CMSSelfieCheckHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CMSSelfieCheckHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CMSSelfieCheck
     */
    @WebEndpoint(name = "CMS_Selfie_CheckHttpPort")
    public CMSSelfieCheck getCMSSelfieCheckHttpPort() {
        return super.getPort(new QName("http://CMS_Selfie_Check", "CMS_Selfie_CheckHttpPort"), CMSSelfieCheck.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CMSSelfieCheck
     */
    @WebEndpoint(name = "CMS_Selfie_CheckHttpPort")
    public CMSSelfieCheck getCMSSelfieCheckHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://CMS_Selfie_Check", "CMS_Selfie_CheckHttpPort"), CMSSelfieCheck.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CMSSELFIECHECKHTTPSERVICE_EXCEPTION!= null) {
            throw CMSSELFIECHECKHTTPSERVICE_EXCEPTION;
        }
        return CMSSELFIECHECKHTTPSERVICE_WSDL_LOCATION;
    }

}
