
package com.checkuser;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CMS_Selfie_Check", targetNamespace = "http://CMS_Selfie_Check")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CMSSelfieCheck {


    /**
     * 
     * @param custInfo
     * @param sys
     * @return
     *     returns src.SysResponseType
     */
    @WebMethod(action = "http://CMS_Selfie_Check/checkCust")
    @WebResult(name = "Sys", targetNamespace = "")
    @RequestWrapper(localName = "checkCust", targetNamespace = "http://CMS_Selfie_Check", className = "src.CheckCust")
    @ResponseWrapper(localName = "checkCustResponse", targetNamespace = "http://CMS_Selfie_Check", className = "src.CheckCustResponse")
    public SysResponseType checkCust(
        @WebParam(name = "Sys", targetNamespace = "")
        SysRequestType sys,
        @WebParam(name = "CustInfo", targetNamespace = "")
        CustInfoType custInfo);

}
